name: Security Scan
on:
  push:
  pull_request: 
jobs:
  analyze:
    name: CodQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3
